### PR TITLE
Show the Splunk logo

### LINKED ISSUE #24: Add support for image-to-ascii to show the Splunk logo
I will give this a try, posting for visibility.

https://github.com/IonicaBizau/image-to-ascii

### PR DESCRIPTION
**Pull request by shakeelmohamed**
This uses the `image-to-ascii` package to show the Splunk logo in ASCII art when the Splunkrepl first runs.

~~This functionality only works if the user has [Graphics Magick](http://www.graphicsmagick.org/) installed. If it's not installed, there is no change in functionality~~ No longer dependent on Graphics Magick

Screenshot:
capturfiles_10

Closes #24

### CODE REVIEW

**Comment by shakeelmohamed** [comment]
We no longer depend on Graphics Magick :ship:

**Comment by shakeelmohamed** [comment]
Note: this doesn't work at all on Windows.

**Comment by glennblock** [comment]
How about just have a non-color version for windows?

**Comment by IonicaBizau** [comment]
@shakeelmohamed `image-to-ascii` is no longer dependent on `graphicsmagick`, tho, that's recommended to be installed (quicker installation). :rocket: 

@glennblock The new version of `image-to-ascii` renders the best possible colors. That means `16` colors in command prompt on Windows and probably 256 in `cygwin`. :art:

**Comment by glennblock** [comment]
@IonicaBizau nice, thanks!

**Comment by glennblock** [comment]
@IonicaBizau fails when I try to install on Windows 10 without graphicsmagick

```
C:\src\splunkrepl>npm install

> lwip2@1.0.1 install C:\src\splunkrepl\node_modules\image-to-ascii\node_modules\image-parser\node_modules\lwipify\node_modules\lwip2
> node scripts/install.js

Installing lwip. If this fails, just install GraphicsMagick (http://www.graphicsmagick.org/).
 events.js:141
> lwip2@1.0.1 install C:\src\splunkrepl\node_modules\image-to-ascii\node_modules\imgpx\node_modules\lwipify\node_modules\lwip2^
> node scripts/install.js
Error: spawn npm ENOENT
Installing lwip. If this fails, just install GraphicsMagick (http://www.graphicsmagick.org/).
events.js:141s.ChildProcess._handle.onexit (internal/child_process.js:178:32)
      throw er; // Unhandled 'error' events:344:16)
      ^nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
Error: spawn npm ENOENTrunMain (module.js:443:11)
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! lwip2@1.0.1 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the lwip2@1.0.1 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the lwip2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lwip2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls lwip2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\src\splunkrepl\npm-debug.log
```

**Comment by IonicaBizau** [comment]
@glennblock Looks like it cannot compile `lwip` on your machine. Do you know any [`lwip`](https://github.com/EyalAr/lwip) alternatives that don't require any binaries and work on all platforms?

**Comment by shakeelmohamed** [comment]
@glennblock this might be a node-gyp issue. @IonicaBizau does this mean every user would need to be setup for compiling C++ modules?

**Comment by IonicaBizau** [comment]
Yes... :cry: On Linux (and OS X, probably) this works pretty smoothly because all the tools are generally preinstalled.

**Comment by glennblock** [comment]
If it is node-gyp an alternative is to have the pre-built binaries in the package and have them copied over in an install script. Several other modules do this like edge which runs this script: https://github.com/tjanczuk/edge/blob/master/tools/install.js as the package.json install script. Basically if it sees that VS is not present / the required build tools, it will just copy the binary to the right place.

Let me think about it.

Ideally the way this is handled, is the module author that delivers the module has an install script with the pre-built binaries.

It may just make sense to just have black and white for windows....

**Pull request closed without merging**
